version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command: --web.enable-lifecycle
      --config.file=/etc/prometheus/prometheus.yml

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  mysql_exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    command:
      - "--mysqld.username=exporter:password"
      - "--mysqld.address=mysql:3306"
    depends_on:
      - mysql
