global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: admin@example.com
        from: alert@example.com
        smarthost: mailhog:1025
        require_tls: false
