version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
      - "9100:9100"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./node_exporter-1.8.2.linux-amd64.tar.gz:/tmp/node_exporter-1.8.2.linux-amd64.tar.gz
    working_dir: /tmp
    entrypoint: sh -c "prometheus --config.file=/etc/prometheus/prometheus.yml &
      tar xvfz node_exporter-1.8.2.linux-amd64.tar.gz &&
      cd node_exporter-1.8.2.linux-amd64 &&
      ./node_exporter"
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
