version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command: --web.enable-lifecycle
      --config.file=/etc/prometheus/prometheus.yml
  httpd:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
  apache_exporter:
    image: bitnami/apache-exporter
    ports:
      - "9117:9117"
    command: --scrape_uri="http://httpd/server-status/?auto"
