version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: --web.enable-lifecycle
      --config.file=/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter
    hostname: prometheus-book
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
